<a href="https://colab.research.google.com/github/NYChase/PyTorch/blob/learnpytorch.io/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
random_tensor_7_7 = torch.rand(7, 7)
print(random_tensor_7_7)

tensor([[0.4031, 0.2100, 0.4478, 0.7208, 0.0432, 0.8158, 0.1088],
        [0.1356, 0.4937, 0.3013, 0.1969, 0.4861, 0.6513, 0.3085],
        [0.0153, 0.7576, 0.0870, 0.0507, 0.5672, 0.0778, 0.6517],
        [0.9615, 0.7280, 0.9379, 0.4645, 0.9921, 0.1970, 0.4086],
        [0.6519, 0.7901, 0.9691, 0.3612, 0.1497, 0.0674, 0.2323],
        [0.1179, 0.8070, 0.4913, 0.3091, 0.1049, 0.4237, 0.4439],
        [0.6365, 0.8627, 0.9580, 0.2132, 0.4315, 0.4360, 0.2149]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
random_tensor_1_7 = torch.rand(1, 7)

# Perform matrix multiplication
# The original tensor is (7, 7) and the new one is (1, 7).
# To multiply, the inner dimensions must match. We can transpose the second tensor
# from (1, 7) to (7, 1) to get a result of (7, 1).
matmul_result = torch.matmul(random_tensor_7_7, random_tensor_1_7.T)
print(matmul_result)

tensor([[1.1994],
        [1.2004],
        [0.9391],
        [1.6908],
        [1.3396],
        [1.3206],
        [1.6608]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor_A = torch.rand(7, 7)
random_tensor_B = torch.rand(1, 7)

# Matrix multiply tensors
matmul_result_seeded = torch.matmul(random_tensor_A, random_tensor_B.T)
print(matmul_result_seeded)
print(matmul_result_seeded.size())

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)
    print("GPU random seed set to 1234.")
else:
    print("No GPU available, cannot set GPU random seed.")

GPU random seed set to 1234.



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"Device: {device}")
    # Create two random tensors on GPU
    tensor_A = torch.rand(2, 3, device=device)
    tensor_B = torch.rand(2, 3, device=device)
    print((tensor_A, tensor_B))
else:
    print("No GPU available.")

Device: cuda
(tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0'), tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0'))



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
if torch.cuda.is_available():
    matmul_result_gpu = torch.matmul(tensor_A, tensor_B.T)
    print(matmul_result_gpu)
    print(matmul_result_gpu.size())
else:
    print("No GPU available to perform matrix multiplication.")

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')
torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
if torch.cuda.is_available():
    max_value = torch.max(matmul_result_gpu)
    print(f"Maximum value: {max_value}")
else:
    print("No GPU available to find the maximum value.")

# Find min
if torch.cuda.is_available():
    min_value = torch.min(matmul_result_gpu)
    print(f"Minimum value: {min_value}")
else:
    print("No GPU available to find the minimum value.")

Maximum value: 0.7667766809463501
Minimum value: 0.27863210439682007


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
if torch.cuda.is_available():
    argmax_value = torch.argmax(matmul_result_gpu)
    print(f"Index of maximum value: {argmax_value}")
else:
    print("No GPU available to find the index of the maximum value.")

# Find arg min
if torch.cuda.is_available():
    argmin_value = torch.argmin(matmul_result_gpu)
    print(f"Index of minimum value: {argmin_value}")
else:
    print("No GPU available to find the index of the minimum value.")

Index of maximum value: 1
Index of minimum value: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
squeezed_tensor = random_tensor.squeeze()

# Print out tensors and their shapes
print(random_tensor, random_tensor.shape)
print(squeezed_tensor, squeezed_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
